Alias: $LNC = http://loinc.org
Alias: $SCT = http://snomed.info/sct
Alias: $SCT_or_SCTINT = http://snomed.info/sct|http://snomed.info/sct/900000000000207008
Alias: $DICOM = http://dicom.nema.org/resources/ontology/DCM

ValueSet: VSRiskBehaviourPhysicalActivity
Id: vs-risk-behaviour-physical-activity
Title: "Physical Activity"
Description: "Physical Activity Status"
* ^experimental = false
* include codes from system $SCT
    where concept descendent-of #68130003

/*ValueSet: VSRiskBehaviourTobaccoSmoker
Id: vs-risk-behaviour-tobacco-smoker
Title: "Tobacco Smoker"
Description: "Tobacco Smoker Status"
* ^experimental = false
* include codes from system $SCT
    where concept descendent-of #365980008*/

CodeSystem: CSIdentifierTypes
Id: cs-identifier-types
Title: "Patient Business Identifier Types"
Description: "Patient Business Identifier Types"
* ^experimental = false
* ^caseSensitive = true
* #SCN "Senior Citizen Number" "Needs definition"
* #PHN "Personal Health Number" "Needs definition"
* #NIC "National Identity Card" "Needs definition"
* #PLOC "Provider Location" "Needs definition"

ValueSet: VSIdentifierTypes
Id: vs-identifier-types
Title: "Patient Business Identifier Types"
Description: "Patient Business Identifier Types"
* ^experimental = false
* include codes from system CSIdentifierTypes

ValueSet: VSFollowUpPlan
Id: vs-follow-up-plan
Title: "Follow-up plan"
Description: "Follow-up plan"
* ^experimental = false
* include codes from system $SCT
    where concept descendent-of #183851006
* $SCT#772071006 "Referral to dentist"
* $SCT#410321003 "Wellness health education, guidance, and counseling"
* $SCT#306110004 "Referral to medical service"

CodeSystem: CSFollowUpReasons
Id: cs-follow-up-reasons
Title: "Follow up at HLC"
Description: "Follow up at Healthy Lifestyle Center"
* ^experimental = false
* ^caseSensitive = true
* #Followed-in-3-years-at-hlc "Followed in 3 years at HLC" "Needs definition"

ValueSet: VSFollowUpReasons
Id: vs-follow-up-reasons
Title: "Follow up at HLC"
Description: "Follow up at Healthy Lifestyle Center"
* ^experimental = false
* include codes from system $SCT
    where concept descendent-of #183616001
* include codes from system CSFollowUpReasons

CodeSystem: CSCVDRiskCategory
Id: cs-cvd-risk-category
Title: "Cardiovascular Risk Categories"
Description: "Cardiovascular risk is expressed as a percentage"
* ^experimental = false
* ^caseSensitive = true
* #Low "Less than 5%" "Needs definition"
* #Moderate "5% to less than 10%" "Needs definition"
* #High "10% to less than 20%" "Needs definition"
* #Very-High "20% to less than 30%" "Needs definition"
* #Critical "Equal or more than 30%" "Needs definition"

ValueSet: VSCVDRiskCategory
Id: vs-cvd-risk-category
Title: "Cardiovascular Risk Categories"
Description: "Cardiovascular risk is expressed as a percentage"
* ^experimental = false
* include codes from system CSCVDRiskCategory

ValueSet: VSMedicalConditions
Id: vs-medical-conditions
Title: "Conditions"
Description: "Represents previous, pre-existing and new conditions."
* ^experimental = false
* $SCT#38341003 "Hypertension"
* $SCT#195967001 "Asthma"
* $SCT#230690007 "Cerebrovascular accident"
* include codes from system $SCT
    where concept descendent-of #73211009

/*ValueSet: VSAllergies
Id: vs-allergies
Title: "Allergies"
Description: "Allergies"
* ^experimental = false
* $SCT#165008002 "Allergy testing not done"
* $SCT#716186003 "No known allergy"
* $SCT#416098002 "Allergy to drug"
* $SCT#426232007 "Environmental allergy"
* $SCT#414285001 "Allergy to food"*/

CodeSystem: CSReasonForEncounter
Id: cs-reason-for-encounter
Title: "Reason For Encounter"
Description: "Encounter reasons."
* ^experimental = false
* ^caseSensitive = true
* #-30 "Medical examin/health eval complete" "Needs definition"
* #-31 "Medical examin/health eval partial" "Needs definition"
* #-32 "Sensitivity test" "Needs definition"
* #-33 "Microbiological/immunological test" "Needs definition"
* #-34 "Blood test" "Needs definition"
* #-35 "Urine test" "Needs definition"
* #-36 "Faeces test" "Needs definition"
* #-37 "Histological/exfoliative cytology" "Needs definition"
* #-38 "Other laboratory test NEC" "Needs definition"
* #-39 "Physical function test" "Needs definition"
* #-40 "Diagnostic endoscopy" "Needs definition"
* #-41 "Diagnostic radiology/imaging" "Needs definition"
* #-42 "Electrical tracing" "Needs definition"
* #-43 "Other diagnostic procedure" "Needs definition"
* #-44 "Preventive immunization/medication" "Needs definition"
* #-45 "Observ/health educat/advice/diet" "Needs definition"
* #-46 "Consultation primary care provider" "Needs definition"
* #-47 "Consultation with specialist" "Needs definition"
* #-48 "Clarification/discussion rfe/demand" "Needs definition"
* #-49 "Other preventive procedure" "Needs definition"
* #-50 "Medication/prescr/renewal/inject" "Needs definition"
* #-51 "I&d/flush/aspiration" "Needs definition"
* #-52 "Exc/remov/biopsy/destruc/debrid/caut" "Needs definition"
* #-53 "Instrument/catheter/intubate/dilate" "Needs definition"
* #-54 "Repair/fix-suture/cast/prosth device" "Needs definition"
* #-55 "Local injection/infiltration" "Needs definition"
* #-56 "Dressing/pressure/compress/tamponade" "Needs definition"
* #-57 "Physical medicine/rehabilitation" "Needs definition"
* #-58 "Therapeutic counselling/listening" "Needs definition"
* #-59 "Other therap proced/minor surg NEC" "Needs definition"
* #-60 "Result test/procedure" "Needs definition"
* #-61 "Result exam/test/lett oth provider" "Needs definition"
* #-62 "Administrative procedure" "Needs definition"
* #-63 "Follow-up encounter unspecified" "Needs definition"
* #-64 "Encounter/prob initiated by provider" "Needs definition"
* #-65 "Enc/prob init by other than pt/prov" "Needs definition"
* #-66 "Referral to non-MD provider" "Needs definition"
* #-67 "Referral to physician/hospital" "Needs definition"
* #-68 "Other referral NEC" "Needs definition"
* #-69 "Other reason for encounter NEC" "Needs definition"
* #A01 "Pain general/multiple sites" "Needs definition"
* #A02 "Chills" "Needs definition"
* #A03 "Fever" "Needs definition"
* #A04 "Weakness/tiredness general" "Needs definition"
* #A05 "Feeling ill" "Needs definition"
* #A06 "Fainting/syncope" "Needs definition"
* #A07 "Coma" "Needs definition"
* #A08 "Swelling" "Needs definition"
* #A09 "Sweating problem" "Needs definition"
* #A10 "Bleeding/haemorrhage NOS" "Needs definition"
* #A11 "Chest pain NOS" "Needs definition"
* #A13 "Concern/fear medical treatment" "Needs definition"
* #A16 "Irritable infant" "Needs definition"
* #A18 "Concern about appearance" "Needs definition"
* #A20 "Euthanasia request/discussion" "Needs definition"
* #A21 "Risk factor for malignancy" "Needs definition"
* #A23 "Risk factor NOS" "Needs definition"
* #A25 "Fear of death/dying" "Needs definition"
* #A26 "NOS" "Needs definition"
* #A27 "Fear of other disease NOS" "Needs definition"
* #A28 "Limited function/disability NOS" "Needs definition"
* #A29 "General symptom/complaint other" "Needs definition"
* #A70 "Tuberculosis" "Needs definition"
* #A71 "Measles" "Needs definition"
* #A72 "Chickenpox" "Needs definition"
* #A73 "Malaria" "Needs definition"
* #A74 "Rubella / Congenital Rubella Syndrome" "Needs definition"
* #A75 "Infectious mononucleosis" "Needs definition"
* #A76 "Viral exanthem other" "Needs definition"
* #A77 "Viral disease other/NOS" "Needs definition"
* #A78 "Infectious disease other/NOS" "Needs definition"
* #A79 "Malignancy NOS" "Needs definition"
* #A80 "Trauma/injury NOS" "Needs definition"
* #A81 "Multiple trauma/injuries" "Needs definition"
* #A82 "Secondary effect of trauma" "Needs definition"
* #A84 "Poisoning by medical agent" "Needs definition"
* #A85 "Adverse effect medical agent" "Needs definition"
* #A86 "Toxic effect non-medicinal substance" "Needs definition"
* #A87 "Complication of medical treatment" "Needs definition"
* #A88 "Adverse effect physical factor" "Needs definition"
* #A89 "Effect prosthetic device" "Needs definition"
* #A90 "Congenital anomaly NOS/multiple" "Needs definition"
* #A91 "Abnormal result investigation NOS" "Needs definition"
* #A92 "Allergy/allergic reaction NOS" "Needs definition"
* #A93 "Premature newborn" "Needs definition"
* #A94 "Perinatal morbidity other" "Needs definition"
* #A95 "Perinatal mortality" "Needs definition"
* #A96 "Death" "Needs definition"
* #A97 "No disease" "Needs definition"
* #A98 "Health maint/preventive medicine" "Needs definition"
* #A99 "Disease/condition unspecnature/site" "Needs definition"
* #B02 "Lymph gland(s) enlarged/painful" "Needs definition"
* #B04 "Blood symptom/complaint" "Needs definition"
* #B25 "Fear of AIDS/HIV" "Needs definition"
* #B26 "Fear cancer blood/lymph" "Needs definition"
* #B27 "Fear blood/lymph disease other" "Needs definition"
* #B28 "Limited function/disability (B)" "Needs definition"
* #B29 "Lymph/immune mech sympt/complt other" "Needs definition"
* #B70 "Lymphadenitis acute" "Needs definition"
* #B71 "Lymphadenitis chronic/non-specific" "Needs definition"
* #B72 "Hodgkin Lymphoma" "Needs definition"
* #B73 "Leukaemia" "Needs definition"
* #B74 "Malignant neoplasm blood other" "Needs definition"
* #B75 "Neoplasm blood benign/unspecified" "Needs definition"
* #B76 "Ruptured spleen traumatic" "Needs definition"
* #B77 "Injury blood/lymph/spleen other" "Needs definition"
* #B78 "Hereditary haemolytic anaemia" "Needs definition"
* #B79 "Congen anomaly blood/lymph other" "Needs definition"
* #B80 "Iron deficiency anaemia" "Needs definition"
* #B81 "Anaemia vit B12/folate deficiency" "Needs definition"
* #B82 "Anaemia other/unspecified" "Needs definition"
* #B83 "Purpura/coagulation defect" "Needs definition"
* #B84 "Unexplained abnormal white cells" "Needs definition"
* #B87 "Splenomegaly" "Needs definition"
* #B90 "HIV-infection/AIDS" "Needs definition"
* #B99 "Blood/lymph/spleen disease other" "Needs definition"
* #D01 "Abdominal pain/cramps general" "Needs definition"
* #D02 "Abdominal pain epigastric" "Needs definition"
* #D03 "Heartburn" "Needs definition"
* #D04 "Rectal/anal pain" "Needs definition"
* #D05 "Perianal itching" "Needs definition"
* #D06 "Abdominal pain localized other" "Needs definition"
* #D07 "Dyspepsia/indigestion" "Needs definition"
* #D08 "Flatulence/gas/belching" "Needs definition"
* #D09 "Nausea" "Needs definition"
* #D10 "Vomiting" "Needs definition"
* #D11 "Diarrhoea" "Needs definition"
* #D12 "Constipation" "Needs definition"
* #D13 "Jaundice" "Needs definition"
* #D14 "Haematemesis/vomiting blood" "Needs definition"
* #D15 "Melaena" "Needs definition"
* #D16 "Rectal bleeding" "Needs definition"
* #D17 "Incontinence of bowel" "Needs definition"
* #D18 "Change in faeces/bowel movements" "Needs definition"
* #D19 "Teeth/gum symptom/complaint" "Needs definition"
* #D20 "Mouth/tongue/lip symptom/complaint" "Needs definition"
* #D21 "Swallowing problem" "Needs definition"
* #D23 "Hepatomegaly" "Needs definition"
* #D24 "Abdominal mass NOS" "Needs definition"
* #D25 "Abdominal distension" "Needs definition"
* #D26 "Fear of cancer of digestive system" "Needs definition"
* #D27 "Fear of digestive disease other" "Needs definition"
* #D28 "Limited function/disability (D)" "Needs definition"
* #D29 "Digestive symptom/complaint other" "Needs definition"
* #D70 "Gastrointestinal infection" "Needs definition"
* #D71 "Mumps" "Needs definition"
* #D72 "Viral hepatitis" "Needs definition"
* #D73 "Gastroenteritis presumed infection" "Needs definition"
* #D74 "Malignant neoplasm stomach" "Needs definition"
* #D75 "Malignant neoplasm colon/rectum" "Needs definition"
* #D76 "Malignant neoplasm pancreas" "Needs definition"
* #D77 "Malignant digestive neopl other/NOS" "Needs definition"
* #D78 "Neoplasm digestive benign/unspecif" "Needs definition"
* #D79 "Foreign body digestive system" "Needs definition"
* #D80 "Injury digestive system other" "Needs definition"
* #D81 "Congenital anomaly digestive system" "Needs definition"
* #D82 "Teeth/gum disease" "Needs definition"
* #D83 "Mouth/tongue/lip disease" "Needs definition"
* #D84 "Oesophagus disease" "Needs definition"
* #D85 "Duodenal ulcer" "Needs definition"
* #D86 "Peptic ulcer other" "Needs definition"
* #D87 "Stomach function disorder" "Needs definition"
* #D88 "Appendicitis" "Needs definition"
* #D89 "Inguinal hernia" "Needs definition"
* #D90 "Hiatus hernia" "Needs definition"
* #D91 "Abdominal hernia other" "Needs definition"
* #D92 "Diverticular disease" "Needs definition"
* #D93 "Irritable bowel syndrome" "Needs definition"
* #D94 "Chronic enteritis/ulcerative colitis" "Needs definition"
* #D95 "Anal fissure/perianal abscess" "Needs definition"
* #D96 "Worms/other parasites" "Needs definition"
* #D97 "Liver disease NOS" "Needs definition"
* #D98 "Cholecystitis/cholelithiasis" "Needs definition"
* #D99 "Disease digestive system other" "Needs definition"
* #F01 "Eye pain" "Needs definition"
* #F02 "Red eye" "Needs definition"
* #F03 "Eye discharge" "Needs definition"
* #F04 "Visual floaters/spots" "Needs definition"
* #F05 "Visual disturbance other" "Needs definition"
* #F13 "Eye sensation abnormal" "Needs definition"
* #F14 "Eye movements abnormal" "Needs definition"
* #F15 "Eye appearance abnormal" "Needs definition"
* #F16 "Eyelid symptom/complaint" "Needs definition"
* #F17 "Glasses symptom/complaint" "Needs definition"
* #F18 "Contact lens symptom/complaint" "Needs definition"
* #F27 "Fear of eye disease" "Needs definition"
* #F28 "Limited function/disability (F)" "Needs definition"
* #F29 "Eye symptom/complaint other" "Needs definition"
* #F70 "Conjunctivitis infectious" "Needs definition"
* #F71 "Conjunctivitis allergic" "Needs definition"
* #F72 "Blepharitis/stye/chalazion" "Needs definition"
* #F73 "Eye infection/inflammation other" "Needs definition"
* #F74 "Neoplasm of eye/adnexa" "Needs definition"
* #F75 "Contusion/haemorrhage eye" "Needs definition"
* #F76 "Foreign body in eye" "Needs definition"
* #F79 "Injury eye other" "Needs definition"
* #F80 "Blocked lacrimal duct of infant" "Needs definition"
* #F81 "Congenital anomaly eye other" "Needs definition"
* #F82 "Detached retina" "Needs definition"
* #F83 "Retinopathy" "Needs definition"
* #F84 "Macular degeneration" "Needs definition"
* #F85 "Corneal ulcer" "Needs definition"
* #F86 "Trachoma" "Needs definition"
* #F91 "Refractive error" "Needs definition"
* #F92 "Cataract" "Needs definition"
* #F93 "Glaucoma" "Needs definition"
* #F94 "Blindness" "Needs definition"
* #F95 "Strabismus" "Needs definition"
* #F99 "Eye/adnexa disease other" "Needs definition"
* #H01 "Ear pain/earache" "Needs definition"
* #H02 "Hearing complaint" "Needs definition"
* #H03 "ringing/buzzing ear" "Needs definition"
* #H04 "Ear discharge" "Needs definition"
* #H05 "Bleeding ear" "Needs definition"
* #H13 "Plugged feeling ear" "Needs definition"
* #H15 "Concern with appearance of ears" "Needs definition"
* #H27 "Fear of ear disease" "Needs definition"
* #H28 "Limited function/disability (H)" "Needs definition"
* #H29 "Ear symptom/complaint other" "Needs definition"
* #H70 "Otitis externa" "Needs definition"
* #H71 "Acute otitis media/myringitis" "Needs definition"
* #H72 "Serous otitis media" "Needs definition"
* #H73 "Eustachian salpingitis" "Needs definition"
* #H74 "Chronic otitis media" "Needs definition"
* #H75 "Neoplasm of ear" "Needs definition"
* #H76 "Foreign body in ear" "Needs definition"
* #H77 "Perforation ear drum" "Needs definition"
* #H78 "Superficial injury of ear" "Needs definition"
* #H79 "Ear injury other" "Needs definition"
* #H80 "Congenital anomaly of ear" "Needs definition"
* #H81 "Excessive ear wax" "Needs definition"
* #H82 "Vertiginous syndrome" "Needs definition"
* #H83 "Otosclerosis" "Needs definition"
* #H84 "Presbyacusis" "Needs definition"
* #H85 "Acoustic trauma" "Needs definition"
* #H86 "Deafness" "Needs definition"
* #H99 "Ear/mastoid disease other" "Needs definition"
* #K01 "Heart pain" "Needs definition"
* #K02 "Pressure/tightness of heart" "Needs definition"
* #K03 "Cardiovascular pain NOS" "Needs definition"
* #K04 "Palpitations/awareness of heart" "Needs definition"
* #K05 "Irregular heartbeat other" "Needs definition"
* #K06 "Prominent veins" "Needs definition"
* #K07 "Swollen ankles/oedema" "Needs definition"
* #K22 "Risk factor cardiovascular disease" "Needs definition"
* #K24 "Fear of heart disease" "Needs definition"
* #K25 "Fear of hypertension" "Needs definition"
* #K27 "Fear cardiovascular disease other" "Needs definition"
* #K28 "Limited function/disability (K)" "Needs definition"
* #K29 "Cardiovascular sympt/complt other" "Needs definition"
* #K70 "Infection of circulatory system" "Needs definition"
* #K71 "Rheumatic fever/heart disease" "Needs definition"
* #K72 "Neoplasm cardiovascular" "Needs definition"
* #K73 "Congenital anomaly cardiovascular" "Needs definition"
* #K74 "Ischaemic heart dis with angina" "Needs definition"
* #K75 "Acute myocardial infarction" "Needs definition"
* #K76 "Ischaemic heart dis without angina" "Needs definition"
* #K77 "Heart failure" "Needs definition"
* #K78 "Atrial fibrillation/flutter" "Needs definition"
* #K79 "Paroxysmal tachycardia" "Needs definition"
* #K80 "Cardiac arrhythmia NOS" "Needs definition"
* #K81 "Heart/arterial murmur NOS" "Needs definition"
* #K82 "Pulmonary heart disease" "Needs definition"
* #K83 "Heart valve disease NOS" "Needs definition"
* #K84 "Heart disease other" "Needs definition"
* #K85 "Elevated blood pressure" "Needs definition"
* #K86 "Hypertension uncomplicated" "Needs definition"
* #K87 "Hypertension complicated" "Needs definition"
* #K88 "Postural hypotension" "Needs definition"
* #K89 "Transient cerebral ischaemia" "Needs definition"
* #K90 "Stroke/cerebrovascular accident" "Needs definition"
* #K91 "Cerebrovascular disease" "Needs definition"
* #K92 "Atherosclerosis/periph vascular dis" "Needs definition"
* #K93 "Pulmonary embolism" "Needs definition"
* #K94 "Phlebitis/thrombophlebitis" "Needs definition"
* #K95 "Varicose veins of leg" "Needs definition"
* #K96 "Haemorrhoids" "Needs definition"
* #K99 "Cardiovascular disease other" "Needs definition"
* #L01 "Neck symptom/complaint" "Needs definition"
* #L02 "Back symptom/complaint" "Needs definition"
* #L03 "Low back symptom/complaint" "Needs definition"
* #L04 "Chest symptom/complaint" "Needs definition"
* #L05 "Flank/axilla symptom/complaint" "Needs definition"
* #L07 "Jaw symptom/complaint" "Needs definition"
* #L08 "Shoulder symptom/complaint" "Needs definition"
* #L09 "Arm symptom/complaint" "Needs definition"
* #L10 "Elbow symptom/complaint" "Needs definition"
* #L11 "Wrist symptom/complaint" "Needs definition"
* #L12 "Hand/finger symptom/complaint" "Needs definition"
* #L13 "Hip symptom/complaint" "Needs definition"
* #L14 "Leg/thigh symptom/complaint" "Needs definition"
* #L15 "Knee symptom/complaint" "Needs definition"
* #L16 "Ankle symptom/complaint" "Needs definition"
* #L17 "Foot/toe symptom/complaint" "Needs definition"
* #L18 "Muscle pain" "Needs definition"
* #L19 "Muscle symptom/complaint NOS" "Needs definition"
* #L20 "Joint symptom/complaint NOS" "Needs definition"
* #L26 "Fear of cancer musculoskeletal" "Needs definition"
* #L27 "Fear of musculoskeletal dis other" "Needs definition"
* #L28 "Limited function/disability (L)" "Needs definition"
* #L29 "Musculoskeletal sympt/complt other" "Needs definition"
* #L70 "Infection of musculoskeletal system" "Needs definition"
* #L71 "Malignant neoplasm musculoskeletal" "Needs definition"
* #L72 "Fracture: radius/ulna" "Needs definition"
* #L73 "Fracture: tibia/fibula" "Needs definition"
* #L74 "Fracture: hand/foot bone" "Needs definition"
* #L75 "Fracture: femur" "Needs definition"
* #L76 "Fracture: other" "Needs definition"
* #L77 "Sprain/strain of ankle" "Needs definition"
* #L78 "Sprain/strain of knee" "Needs definition"
* #L79 "Sprain/strain of joint NOS" "Needs definition"
* #L80 "Dislocation/subluxation" "Needs definition"
* #L81 "Injury musculoskeletal NOS" "Needs definition"
* #L82 "Congenital anomaly musculoskeletal" "Needs definition"
* #L83 "Neck syndrome" "Needs definition"
* #L84 "Back syndrome without radiat pain" "Needs definition"
* #L85 "Acquired deformity of spine" "Needs definition"
* #L86 "Back syndrome with radiating pain" "Needs definition"
* #L87 "Bursitis/tendinitis/synovitis NOS" "Needs definition"
* #L88 "Rheumatoid/seropositive arthritis" "Needs definition"
* #L89 "Osteoarthrosis of hip" "Needs definition"
* #L90 "Osteoarthrosis of knee" "Needs definition"
* #L91 "Osteoarthrosis other" "Needs definition"
* #L92 "Shoulder syndrome" "Needs definition"
* #L93 "Tennis elbow" "Needs definition"
* #L94 "Osteochondrosis" "Needs definition"
* #L95 "Osteoporosis" "Needs definition"
* #L96 "Acute internal damage knee" "Needs definition"
* #L97 "Neoplasm musculoskel benign/unspec" "Needs definition"
* #L98 "Acquired deformity of limb" "Needs definition"
* #L99 "Musculoskeletal disease other" "Needs definition"
* #N01 "Headache" "Needs definition"
* #N03 "Pain face" "Needs definition"
* #N04 "Restless legs" "Needs definition"
* #N05 "Tingling fingers/feet/toes" "Needs definition"
* #N06 "Sensation disturbance other" "Needs definition"
* #N07 "Convulsion/seizure" "Needs definition"
* #N08 "Abnormal involuntary movements" "Needs definition"
* #N16 "Disturbance of smell/taste" "Needs definition"
* #N17 "Vertigo/dizziness" "Needs definition"
* #N18 "Paralysis/weakness" "Needs definition"
* #N19 "Speech disorder" "Needs definition"
* #N26 "Fear cancer neurological system" "Needs definition"
* #N27 "Fear of neurological disease other" "Needs definition"
* #N28 "Limited function/disability (N)" "Needs definition"
* #N29 "Neurological sympt/complt other" "Needs definition"
* #N70 "Poliomyelitis" "Needs definition"
* #N71 "Meningitis / Encephalitis" "Needs definition"
* #N72 "Tetanus" "Needs definition"
* #N73 "Neurological infection other" "Needs definition"
* #N74 "Malignant neoplasm nervous system" "Needs definition"
* #N75 "Benign neoplasm nervous system" "Needs definition"
* #N76 "Neoplasm nervous system unspecified" "Needs definition"
* #N79 "Concussion" "Needs definition"
* #N80 "Head injury other" "Needs definition"
* #N81 "Injury nervous system other" "Needs definition"
* #N85 "Congenital anomaly neurological" "Needs definition"
* #N86 "Multiple sclerosis" "Needs definition"
* #N87 "Parkinsonism" "Needs definition"
* #N88 "Epilepsy" "Needs definition"
* #N89 "Migraine" "Needs definition"
* #N90 "Cluster headache" "Needs definition"
* #N91 "Facial paralysis/bell's palsy" "Needs definition"
* #N92 "Trigeminal neuralgia" "Needs definition"
* #N93 "Carpal tunnel syndrome" "Needs definition"
* #N94 "Peripheral neuritis/neuropathy" "Needs definition"
* #N95 "Tension headache" "Needs definition"
* #N99 "Neurological disease other" "Needs definition"
* #P01 "Feeling anxious/nervous/tense" "Needs definition"
* #P02 "Acute stress reaction" "Needs definition"
* #P03 "Feeling depressed" "Needs definition"
* #P04 "Feeling/behaving irritable/angry" "Needs definition"
* #P05 "feeling/behaving old" "Needs definition"
* #P06 "Sleep disturbance" "Needs definition"
* #P07 "Sexual desire reduced" "Needs definition"
* #P08 "Sexual fulfilment reduced" "Needs definition"
* #P09 "Sexual preference concern" "Needs definition"
* #P10 "Stammering/stuttering/tic" "Needs definition"
* #P11 "Eating problem in child" "Needs definition"
* #P12 "Bedwetting/enuresis" "Needs definition"
* #P13 "Encopresis/bowel training problem" "Needs definition"
* #P15 "Chronic alcohol abuse" "Needs definition"
* #P16 "Acute alcohol abuse" "Needs definition"
* #P17 "Tobacco abuse" "Needs definition"
* #P18 "Medication abuse" "Needs definition"
* #P19 "Drug abuse" "Needs definition"
* #P20 "Memory disturbance" "Needs definition"
* #P22 "Child behaviour symptom/complaint" "Needs definition"
* #P23 "Adolescent behaviour sympt/compl" "Needs definition"
* #P24 "Specific learning problem" "Needs definition"
* #P25 "Phase of life problem adult" "Needs definition"
* #P27 "Fear of mental disorder" "Needs definition"
* #P28 "Limited function/disability (P)" "Needs definition"
* #P29 "Psychological sympt/compl other" "Needs definition"
* #P70 "Dementia" "Needs definition"
* #P71 "Organic psychosis other" "Needs definition"
* #P72 "Schizophrenia" "Needs definition"
* #P73 "Affective psychosis" "Needs definition"
* #P74 "Anxiety disorder/anxiety state" "Needs definition"
* #P75 "Somatization disorder" "Needs definition"
* #P76 "Depressive disorder" "Needs definition"
* #P77 "Suicide/suicide attempt" "Needs definition"
* #P78 "Neuraesthenia/surmenage" "Needs definition"
* #P79 "Phobia/compulsive disorder" "Needs definition"
* #P80 "Personality disorder" "Needs definition"
* #P81 "Hyperkinetic disorder" "Needs definition"
* #P82 "Post-traumatic stress disorder" "Needs definition"
* #P85 "Mental retardation" "Needs definition"
* #P86 "Anorexia nervosa/bulimia" "Needs definition"
* #P98 "Psychosis NOS/other" "Needs definition"
* #P99 "Psychological disorders other" "Needs definition"
* #R01 "Pain respiratory system" "Needs definition"
* #R02 "Shortness of breath/dyspnoea" "Needs definition"
* #R03 "Wheezing" "Needs definition"
* #R04 "Breathing problem other" "Needs definition"
* #R05 "Cough" "Needs definition"
* #R06 "Nose bleed/epistaxis" "Needs definition"
* #R07 "Sneezing/nasal congestion" "Needs definition"
* #R08 "Nose symptom/complaint other" "Needs definition"
* #R09 "Sinus symptom/complaint" "Needs definition"
* #R21 "Throat symptom/complaint" "Needs definition"
* #R23 "Voice symptom/complaint" "Needs definition"
* #R24 "Haemoptysis" "Needs definition"
* #R25 "Sputum/phlegm abnormal" "Needs definition"
* #R26 "Fear cancer respiratory system" "Needs definition"
* #R27 "Fear of respiratory disease other" "Needs definition"
* #R28 "Limited function/disability (R)" "Needs definition"
* #R29 "Respiratory symptom/complaint other" "Needs definition"
* #R71 "Whooping cough" "Needs definition"
* #R72 "Strep throat" "Needs definition"
* #R73 "Boil/abscess nose" "Needs definition"
* #R74 "Upper respiratory infection acute" "Needs definition"
* #R75 "Sinusitis acute/chronic" "Needs definition"
* #R76 "Tonsillitis acute" "Needs definition"
* #R77 "Laryngitis/tracheitis acute" "Needs definition"
* #R78 "Acute bronchitis/bronchiolitis" "Needs definition"
* #R79 "Chronic bronchitis" "Needs definition"
* #R80 "Influenza" "Needs definition"
* #R81 "Pneumonia" "Needs definition"
* #R82 "Pleurisy/pleural effusion" "Needs definition"
* #R83 "Respiratory infection other" "Needs definition"
* #R84 "Malignant neoplasm bronchus/lung" "Needs definition"
* #R85 "Malignant neopl respiratory other" "Needs definition"
* #R86 "Benign neoplasm respiratory" "Needs definition"
* #R87 "Foreign body nose/larynx/bronchus" "Needs definition"
* #R88 "Injury respiratory other" "Needs definition"
* #R89 "Congenital anomaly respiratory" "Needs definition"
* #R90 "Hypertrophy tonsils/adenoids" "Needs definition"
* #R92 "Neoplasm respiratory unspecified" "Needs definition"
* #R95 "Chron obstructive pulmonary disease" "Needs definition"
* #R96 "Asthma" "Needs definition"
* #R97 "Allergic rhinitis" "Needs definition"
* #R98 "Hyperventilation syndrome" "Needs definition"
* #R99 "Respiratory disease other" "Needs definition"
* #S01 "Pain/tenderness of skin" "Needs definition"
* #S02 "Pruritus" "Needs definition"
* #S03 "Warts" "Needs definition"
* #S04 "Lump/swelling localized" "Needs definition"
* #S05 "Lumps/swellings generalized" "Needs definition"
* #S06 "Rash localized" "Needs definition"
* #S07 "Rash generalized" "Needs definition"
* #S08 "Skin colour change" "Needs definition"
* #S09 "Infected finger/toe" "Needs definition"
* #S10 "Boil/carbuncle" "Needs definition"
* #S11 "Skin infection post-traumatic" "Needs definition"
* #S12 "Insect bite/sting" "Needs definition"
* #S13 "Animal/human bite" "Needs definition"
* #S14 "Burn/scald" "Needs definition"
* #S15 "Foreign body in skin" "Needs definition"
* #S16 "Bruise/contusion" "Needs definition"
* #S17 "Abrasion/scratch/blister" "Needs definition"
* #S18 "Laceration/cut" "Needs definition"
* #S19 "Skin injury other" "Needs definition"
* #S20 "Corn/callosity" "Needs definition"
* #S21 "Skin texture symptom/complaint" "Needs definition"
* #S22 "Nail symptom/complaint" "Needs definition"
* #S23 "Hair loss/baldness" "Needs definition"
* #S24 "Hair/scalp symptom/complaint other" "Needs definition"
* #S26 "Fear of cancer of skin" "Needs definition"
* #S27 "Fear of skin disease other" "Needs definition"
* #S28 "Limited function/disability (S)" "Needs definition"
* #S29 "Skin symptom/complaint other" "Needs definition"
* #S70 "Herpes zoster" "Needs definition"
* #S71 "Herpes simplex" "Needs definition"
* #S72 "Scabies/other acariasis" "Needs definition"
* #S73 "Pediculosis/skin infestation other" "Needs definition"
* #S74 "Dermatophytosis" "Needs definition"
* #S75 "Moniliasis/candidiasis skin" "Needs definition"
* #S76 "Skin infection other" "Needs definition"
* #S77 "Malignant neoplasm of skin" "Needs definition"
* #S78 "Lipoma" "Needs definition"
* #S79 "Neoplasm skin benign/unspecified" "Needs definition"
* #S80 "Solar keratosis/sunburn" "Needs definition"
* #S81 "Haemangioma/lymphangioma" "Needs definition"
* #S82 "Naevus/mole" "Needs definition"
* #S83 "Congenital skin anomaly other" "Needs definition"
* #S84 "Impetigo" "Needs definition"
* #S85 "Pilonidal cyst/fistula" "Needs definition"
* #S86 "Dermatitis seborrhoeic" "Needs definition"
* #S87 "Dermatitis/atopic eczema" "Needs definition"
* #S88 "Dermatitis contact/allergic" "Needs definition"
* #S89 "Diaper rash" "Needs definition"
* #S90 "Pityriasis rosea" "Needs definition"
* #S91 "Psoriasis" "Needs definition"
* #S92 "Sweat gland disease" "Needs definition"
* #S93 "Sebaceous cyst" "Needs definition"
* #S94 "Ingrowing nail" "Needs definition"
* #S95 "Molluscum contagiosum" "Needs definition"
* #S96 "Acne" "Needs definition"
* #S97 "Chronic ulcer skin" "Needs definition"
* #S98 "Urticaria" "Needs definition"
* #S99 "Skin disease other" "Needs definition"
* #T01 "Excessive thirst" "Needs definition"
* #T02 "Excessive appetite" "Needs definition"
* #T03 "Loss of appetite" "Needs definition"
* #T04 "Feeding problem of infant/child" "Needs definition"
* #T05 "Feeding problem of adult" "Needs definition"
* #T07 "Weight gain" "Needs definition"
* #T08 "Weight loss" "Needs definition"
* #T10 "Growth delay" "Needs definition"
* #T11 "Dehydration" "Needs definition"
* #T26 "Fear of cancer of endocrine system" "Needs definition"
* #T27 "Fear endocrine/metabol disease other" "Needs definition"
* #T28 "Limited function/disability (T)" "Needs definition"
* #T29 "Endocr/metab/nutr sympt/compl other" "Needs definition"
* #T70 "Endocrine infection" "Needs definition"
* #T71 "Malignant neoplasm thyroid" "Needs definition"
* #T72 "Benign neoplasm thyroid" "Needs definition"
* #T73 "Neoplasm endocrine other/unspecified" "Needs definition"
* #T78 "Thyroglossal duct/cyst" "Needs definition"
* #T80 "Congen anomaly endocrine/metabolic" "Needs definition"
* #T81 "Goitre" "Needs definition"
* #T82 "Obesity" "Needs definition"
* #T83 "Overweight" "Needs definition"
* #T85 "Hyperthyroidism/thyrotoxicosis" "Needs definition"
* #T86 "Hypothyroidism/myxoedema" "Needs definition"
* #T87 "Hypoglycaemia" "Needs definition"
* #T89 "Diabetes insulin dependent" "Needs definition"
* #T90 "Diabetes non-insulin dependent" "Needs definition"
* #T91 "Vitamin/nutritional deficiency" "Needs definition"
* #T92 "Gout" "Needs definition"
* #T93 "Lipid disorder" "Needs definition"
* #T99 "Endocr/metab/nutrit disease other" "Needs definition"
* #U01 "Dysuria/painful urination" "Needs definition"
* #U02 "Urinary frequency/urgency" "Needs definition"
* #U04 "Incontinence urine" "Needs definition"
* #U05 "Urination problems other" "Needs definition"
* #U06 "Haematuria" "Needs definition"
* #U07 "Urine symptom/complaint other" "Needs definition"
* #U08 "Urinary retention" "Needs definition"
* #U13 "Bladder symptom/complaint other" "Needs definition"
* #U14 "Kidney symptom/complaint" "Needs definition"
* #U26 "Fear of cancer of urinary system" "Needs definition"
* #U27 "Fear of urinary disease other" "Needs definition"
* #U28 "Limited function/disability (U)" "Needs definition"
* #U29 "Urinary symptom/complaint other" "Needs definition"
* #U70 "Pyelonephritis/pyelitis" "Needs definition"
* #U71 "Cystitis/urinary infection other" "Needs definition"
* #U72 "Urethritis" "Needs definition"
* #U75 "Malignant neoplasm of kidney" "Needs definition"
* #U76 "Malignant neoplasm of bladder" "Needs definition"
* #U77 "Malignant neopl urinary tract other" "Needs definition"
* #U78 "Benign neoplasm urinary tract" "Needs definition"
* #U79 "Neoplasm urinary tract unspecified" "Needs definition"
* #U80 "Injury urinary tract" "Needs definition"
* #U85 "Congenital anomaly urinary tract" "Needs definition"
* #U88 "Glomerulonephritis/nephrosis" "Needs definition"
* #U90 "Orthostatic albuminuria/proteinuria" "Needs definition"
* #U95 "Urinary calculus" "Needs definition"
* #U98 "Abnormal urine test NOS" "Needs definition"
* #U99 "Urinary disease other" "Needs definition"
* #W01 "Question of pregnancy" "Needs definition"
* #W02 "Fear of pregnancy" "Needs definition"
* #W03 "Antepartum bleeding" "Needs definition"
* #W05 "Pregnancy vomiting/nausea" "Needs definition"
* #W10 "Contraception postcoital" "Needs definition"
* #W11 "Contraception oral" "Needs definition"
* #W12 "Contraception intrauterine" "Needs definition"
* #W13 "Sterilization female" "Needs definition"
* #W14 "Contraception female other" "Needs definition"
* #W15 "Infertility/subfertility female" "Needs definition"
* #W17 "Post-partum bleeding" "Needs definition"
* #W18 "Post-partum symptom/complaint other" "Needs definition"
* #W19 "Lactation symptom/complaint" "Needs definition"
* #W21 "Concern with body image in pregnancy" "Needs definition"
* #W27 "Fear of complications of pregnancy" "Needs definition"
* #W28 "Limited function/disability (W)" "Needs definition"
* #W29 "Pregnancy symptom/complaint other" "Needs definition"
* #W70 "Puerperal infection/sepsis" "Needs definition"
* #W71 "Other infect complic pregn/puerp" "Needs definition"
* #W72 "Malignant neopl related to pregnancy" "Needs definition"
* #W73 "Benign/unspecif neopl relat to pregn" "Needs definition"
* #W75 "Injury complicating pregnancy" "Needs definition"
* #W76 "Congen anom complicating pregnancy" "Needs definition"
* #W78 "Pregnancy" "Needs definition"
* #W79 "Unwanted pregnancy" "Needs definition"
* #W80 "Ectopic pregnancy" "Needs definition"
* #W81 "Toxaemia of pregnancy" "Needs definition"
* #W82 "Abortion spontaneous" "Needs definition"
* #W83 "Abortion induced" "Needs definition"
* #W84 "Pregnancy high risk" "Needs definition"
* #W85 "Gestational diabetes" "Needs definition"
* #W90 "Uncompl labour/delivery livebirth" "Needs definition"
* #W91 "Uncompl labour/delivery stillbirth" "Needs definition"
* #W92 "Compl labour/ delivery livebirth" "Needs definition"
* #W93 "Compl labour/delivery stillbirth" "Needs definition"
* #W94 "Puerperal mastitis" "Needs definition"
* #W95 "Breast dis in pregn/puerperium other" "Needs definition"
* #W96 "Complications of puerperium other" "Needs definition"
* #W99 "Disorder of pregn/delivery other" "Needs definition"
* #X01 "Genital pain female" "Needs definition"
* #X02 "Menstrual pain" "Needs definition"
* #X03 "Intermenstrual pain" "Needs definition"
* #X04 "Painful intercourse female" "Needs definition"
* #X05 "Menstruation absent/scanty" "Needs definition"
* #X06 "Menstruation excessive" "Needs definition"
* #X07 "Menstruation irregular/frequent" "Needs definition"
* #X08 "Intermenstrual bleeding" "Needs definition"
* #X09 "Premenstrual symptom/complaint" "Needs definition"
* #X10 "Postponement of menstruation" "Needs definition"
* #X11 "Menopausal symptom/complaint" "Needs definition"
* #X12 "Postmenopausal bleeding" "Needs definition"
* #X13 "Postcoital bleeding" "Needs definition"
* #X14 "Vaginal discharge" "Needs definition"
* #X15 "Vaginal symptom/complaint other" "Needs definition"
* #X16 "Vulval symptom/complaint" "Needs definition"
* #X17 "Pelvis symptom/complaint female" "Needs definition"
* #X18 "Breast pain female" "Needs definition"
* #X19 "Breast lump/mass female" "Needs definition"
* #X20 "Nipple symptom/complaint female" "Needs definition"
* #X21 "Breast sympt/compl female other" "Needs definition"
* #X22 "Concern breast appearance fema" "Needs definition"
* #X23 "Fear sexually transm dis female" "Needs definition"
* #X24 "Fear of sexual dysfunction female" "Needs definition"
* #X25 "Fear of genital cancer female" "Needs definition"
* #X26 "Fear of breast cancer female" "Needs definition"
* #X27 "Fear genital/breast dis female other" "Needs definition"
* #X28 "Limited function/disability (X)" "Needs definition"
* #X29 "Genital sympt/compl female other" "Needs definition"
* #X70 "Syphilis female" "Needs definition"
* #X71 "Gonorrhoea female" "Needs definition"
* #X72 "Genital candidiasis female" "Needs definition"
* #X73 "Genital trichomoniasis female" "Needs definition"
* #X74 "Pelvic inflammatory disease" "Needs definition"
* #X75 "Malignant neoplasm cervix" "Needs definition"
* #X76 "Malignant neoplasm breast female" "Needs definition"
* #X77 "Malignant neopl genital female other" "Needs definition"
* #X78 "Fibromyoma uterus" "Needs definition"
* #X79 "Benign neoplasm breast female" "Needs definition"
* #X80 "Benign neoplasm female genital" "Needs definition"
* #X81 "Genital neopl female other/unspecif" "Needs definition"
* #X82 "Injury genital female" "Needs definition"
* #X83 "Congenital anomaly genital female" "Needs definition"
* #X84 "Vaginitis/vulvitis NOS" "Needs definition"
* #X85 "Cervical disease NOS" "Needs definition"
* #X86 "Abnormal cervix smear" "Needs definition"
* #X87 "Uterovaginal prolapse" "Needs definition"
* #X88 "Fibrocystic disease breast" "Needs definition"
* #X89 "Premenstrual tension syndrome" "Needs definition"
* #X90 "Genital herpes female" "Needs definition"
* #X91 "Condylomata acuminata female" "Needs definition"
* #X92 "Chlamydia infection genital female" "Needs definition"
* #X99 "Genital disease female other" "Needs definition"
* #Y01 "Pain in penis" "Needs definition"
* #Y02 "Pain in testis/scrotum" "Needs definition"
* #Y03 "Urethral discharge male" "Needs definition"
* #Y04 "Penis symptom/complaint other" "Needs definition"
* #Y05 "Scrotum/testis sympt/compl other" "Needs definition"
* #Y06 "Prostate symptom/complaint" "Needs definition"
* #Y07 "Impotence NOS" "Needs definition"
* #Y08 "Sexual function sympt/compl male" "Needs definition"
* #Y10 "Infertility/subfertility male" "Needs definition"
* #Y13 "Sterilization male" "Needs definition"
* #Y14 "Family planning male other" "Needs definition"
* #Y16 "Breast symptom/complaint male" "Needs definition"
* #Y24 "Fear of sexual dysfunction male" "Needs definition"
* #Y25 "Fear sexually transm disease male" "Needs definition"
* #Y26 "Fear of genital cancer male" "Needs definition"
* #Y27 "Fear of genital disease male other" "Needs definition"
* #Y28 "Limited function/disability (Y)" "Needs definition"
* #Y29 "Genital symptom/complaint male other" "Needs definition"
* #Y70 "Syphilis male" "Needs definition"
* #Y71 "Gonorrhoea male" "Needs definition"
* #Y72 "Genital herpes male" "Needs definition"
* #Y73 "Prostatitis/seminal vesiculitis" "Needs definition"
* #Y74 "Orchitis/epididymitis" "Needs definition"
* #Y75 "Balanitis" "Needs definition"
* #Y76 "Condylomata acuminata male" "Needs definition"
* #Y77 "Malignant neoplasm prostate" "Needs definition"
* #Y78 "Malign neopl male genital other" "Needs definition"
* #Y79 "Benign/unspecif neopl male genital" "Needs definition"
* #Y80 "Injury male genital" "Needs definition"
* #Y81 "Phimosis/redundant prepuce" "Needs definition"
* #Y82 "Hypospadias" "Needs definition"
* #Y83 "Undescended testicle" "Needs definition"
* #Y84 "Congenital genital anom male other" "Needs definition"
* #Y85 "Benign prostatic hypertrophy" "Needs definition"
* #Y86 "Hydrocoele" "Needs definition"
* #Y99 "Genital disease male other" "Needs definition"
* #Z01 "Poverty/financial problem" "Needs definition"
* #Z02 "Food/water problem" "Needs definition"
* #Z03 "Housing/neighbourhood problem" "Needs definition"
* #Z04 "Social cultural problem" "Needs definition"
* #Z05 "Work problem" "Needs definition"
* #Z06 "Unemployment problem" "Needs definition"
* #Z07 "Education problem" "Needs definition"
* #Z08 "Social welfare problem" "Needs definition"
* #Z09 "Legal problem" "Needs definition"
* #Z10 "Health care system problem" "Needs definition"
* #Z11 "Compliance/being ill problem" "Needs definition"
* #Z12 "Relationship problem with partner" "Needs definition"
* #Z13 "Partner's behaviour problem" "Needs definition"
* #Z14 "Partner illness problem" "Needs definition"
* #Z15 "Loss/death of partner problem" "Needs definition"
* #Z16 "Relationship problem with child" "Needs definition"
* #Z18 "Illness problem with child" "Needs definition"
* #Z19 "Loss/death of child problem" "Needs definition"
* #Z20 "Relationship problem parent/fam memb" "Needs definition"
* #Z21 "Behaviour problem parent/fam memb" "Needs definition"
* #Z22 "Illness problem parent/family memb" "Needs definition"
* #Z23 "Loss/death parent/fam memb problem" "Needs definition"
* #Z24 "Relationship problem friend" "Needs definition"
* #Z25 "Assault/harmful event problem" "Needs definition"
* #Z27 "Fear of a social problem" "Needs definition"
* #Z28 "Limited function/disability (Z)" "Needs definition"
* #Z29 "Social problem NOS" "Needs definition"
* #LKRFE01 "Road Traffic Accident" "Needs definition"
* #LKRFE02 "Fall from hight" "Needs definition"
* #LKRFE03 "Fall on ground" "Needs definition"
* #LKRFE04 "Cut injury - minor" "Needs definition"
* #LKRFE05 "Cut injury -major" "Needs definition"
* #LKRFE06 "Assult" "Needs definition"
* #LKRFE07 "Firearm injury" "Needs definition"
* #LKRFE08 "Blunt trauma" "Needs definition"
* #LKRFE09 "Penetrating injury" "Needs definition"
* #LKRFE10 "Self inflicted injury" "Needs definition"
* #LKRFE11 "Animal attack" "Needs definition"
* #LKRFE12 "Animal bite" "Needs definition"
* #LKRFE13 "Head injury" "Needs definition"
* #LKRFE14 "Drowning" "Needs definition"
* #LKRFE15 "Allergy" "Needs definition"
* #LKRFE16 "Poisoning" "Needs definition"
* #LKRFE17 "Crush injury" "Needs definition"
* #LKRFE18 "Electric shock" "Needs definition"
* #LKRFE19 "Fracture - upper limb" "Needs definition"
* #LKRFE20 "Fracture lower limb" "Needs definition"
* #LKRFE21 "Hand injury" "Needs definition"
* #LKRFE22 "Foot injury" "Needs definition"
* #LKRFE23 "Ocupational injury" "Needs definition"
* #LKRFE24 "Other" "Needs definition"
* #LKRFE25 "Road Traffic Accident" "Needs definition"
* #LKRFE26 "Fall from hight" "Needs definition"
* #LKRFE27 "Fall on ground" "Needs definition"
* #LKRFE28 "Cut injury - minor" "Needs definition"
* #LKRFE29 "Cut injury -major" "Needs definition"
* #LKRFE30 "Assult" "Needs definition"
* #LKRFE31 "Firearm injury" "Needs definition"
* #LKRFE32 "Blunt trauma" "Needs definition"
* #LKRFE33 "Penetrating injury" "Needs definition"
* #LKRFE34 "Self inflicted injury" "Needs definition"
* #LKRFE35 "Animal attack" "Needs definition"
* #LKRFE36 "Animal bite" "Needs definition"
* #LKRFE37 "Head injury" "Needs definition"
* #LKRFE38 "Drowning" "Needs definition"
* #LKRFE39 "Allergy" "Needs definition"
* #LKRFE40 "Poisoning" "Needs definition"
* #LKRFE41 "Crush injury" "Needs definition"
* #LKRFE42 "Electric shock" "Needs definition"
* #LKRFE43 "Fracture - upper limb" "Needs definition"
* #LKRFE44 "Fracture lower limb" "Needs definition"
* #LKRFE45 "Hand injury" "Needs definition"
* #LKRFE46 "Foot injury" "Needs definition"
* #LKRFE47 "Ocupational injury" "Needs definition"
* #LKRFE48 "Other" "Needs definition"
* #LKRFE49 "Dental pain" "Needs definition"
* #LKRFE50 "Polyarthritis" "Needs definition"
* #LKRFE51 "Monoarthritis" "Needs definition"
* #LKRFE52 "Sore throat" "Needs definition"
* #LKRFE53 "Dental abscess" "Needs definition"
* #LKRFE54 "Investigated for abdominal pain" "Needs definition"
* #LKRFE55 "wound" "Needs definition"
* #LKRFE56 "Abscess" "Needs definition"
* #LKRFE57 "cellulitis" "Needs definition"
* #LKRFE58 "Ankle oedema" "Needs definition"
* #LKRFE59 "Menorrhagia" "Needs definition"
* #LKRFE60 "Hypothyroidism" "Needs definition"
* #LKRFE61 "Foot pain" "Needs definition"
* #LKRFE62 "Lumbar pain" "Needs definition"
* #LKRFE63 "Heel pain" "Needs definition"
* #LKRFE64 "Insomnia" "Needs definition"
* #LKRFE65 "Cold" "Needs definition"
* #LKRFE66 "present with report" "Needs definition"
* #LKRFE67 "for C & D" "Needs definition"
* #LKRFE68 "Developmental delay" "Needs definition"
* #LKRFE69 "Loose stools" "Needs definition"
* #LKRFE70 "requested to check blood pressure" "Needs definition"
* #LKRFE71 "Nail prick" "Needs definition"
* #LKRFE72 "Hip pain" "Needs definition"
* #LKRFE73 "Requested to follow up" "Needs definition"
* #LKRFE74 "Sweat rash" "Needs definition"
* #LKRFE75 "For investigations" "Needs definition"
* #LKRFE76 "PV bleeding" "Needs definition"
* #LKRFE77 "RIF pain" "Needs definition"
* #LKRFE78 "Hey fever" "Needs definition"
* #LKRFE79 "Allergic rhinitis" "Needs definition"
* #LKRFE80 "Foreign body in throat" "Needs definition"
* #LKRFE81 "Trigger finger" "Needs definition"
* #LKRFE82 "Gasteroenteritis" "Needs definition"
* #LKRFE83 "For suture removal" "Needs definition"
* #LKRFE84 "Pain in hand" "Needs definition"
* #LKRFE85 "For referring to clinic" "Needs definition"
* #LKRFE86 "inter digital rash" "Needs definition"
* #LKRFE87 "interdigital rash" "Needs definition"
* #LKRFE88 "Left sided chest pain" "Needs definition"
* #LKRFE89 "Cellulitis" "Needs definition"
* #LKRFE90 "For ordering investigation" "Needs definition"
* #LKRFE91 "Chickenpox confirmed" "Needs definition"
* #LKRFE92 "Body pain" "Needs definition"
* #LKRFE93 "Reduced vision" "Needs definition"
* #LKRFE94 "Callosity" "Needs definition"
* #LKRFE95 "Oligomenorrhoea" "Needs definition"
* #LKRFE96 "Erectyle impotence" "Needs definition"
* #LKRFE97 "Numbness of feet" "Needs definition"
* #LKRFE98 "Urine frequency" "Needs definition"
* #LKRFE99 "Hand pain" "Needs definition"
* #LKRFE100 "For Erythropoietin injection" "Needs definition"
* #LKRFE101 "A fever" "Needs definition"
* #LKRFE102 "Removed due to wrong entry" "Needs definition"
* #LKRFE103 "Dandruff" "Needs definition"
* #LKRFE104 "PR bleeding" "Needs definition"
* #LKRFE105 "lower limb pain" "Needs definition"
* #LKRFE106 "Demo data" "Needs definition"
* #LKRFE107 "Polyurea" "Needs definition"
* #LKRFE108 "Planter faciaitis" "Needs definition"
* #LKRFE109 "Runny nose" "Needs definition"
* #LKRFE110 "Cholera" "Needs definition"
* #LKRFE111 "Plague" "Needs definition"
* #LKRFE112 "Yellow Fever" "Needs definition"
* #LKRFE113 "Acute Poliomyelitis" "Needs definition"
* #LKRFE114 "Acute Flaccid Paralysis" "Needs definition"
* #LKRFE115 "Dengue Fever" "Needs definition"
* #LKRFE116 "Dengue haemorhagic Fever" "Needs definition"
* #LKRFE117 "Diptheria" "Needs definition"
* #LKRFE118 "Dysentary" "Needs definition"
* #LKRFE119 "Encephalitis" "Needs definition"
* #LKRFE120 "Enteric Fever" "Needs definition"
* #LKRFE121 "Food Poisoning" "Needs definition"
* #LKRFE122 "Rabies" "Needs definition"
* #LKRFE123 "Leptospirosis" "Needs definition"
* #LKRFE124 "Fever Continued for 7 days or more" "Needs definition"
* #LKRFE125 "Neonatal Tetanus" "Needs definition"
* #LKRFE126 "Typhus fever" "Needs definition"
* #LKRFE127 "COVID 19 Suspected" "Needs definition"
* #LKRFE128 "COVID 19 INFECTED" "Needs definition"
* #LKRFE129 "COVID 19 WITH COMORBIDITIES" "Needs definition"
* #LKRFE130 "Non Covid admission" "Needs definition"
* #LKRFE131 "Heamodialysis" "Needs definition"
* #LKRFE132 "Diagnostic Radiology" "Needs definition"
* #LKRFE133 "HDU Care" "Needs definition"

ValueSet: VSReasonForEncounter
Id: vs-reason-for-encounter
Title: "Reason For Encounter"
Description: "Encounter reasons."
* ^experimental = false
* include codes from system CSReasonForEncounter

CodeSystem: CSProcedures
Id: cs-procedure
Title: "Procedures"
Description: "Other Procedures"
* ^experimental = false
* ^caseSensitive = true
* #ARV-0.1ml-2-sites "ARV 0.1 ml ID x 2 Sites" "Needs definition"
* #ARV-0.1ml-4-sites "ARV 0.1 ml ID x 4 Sites" "Needs definition"
* #Benzathine-Penicillin-Injection "Benzathine Penicillin Injection" "Needs definition"
* #Cleaning-and-Dressing "Cleaning and Dressing" "Needs definition"
* #Erythropoietin "Erythropoietin" "Needs definition"
* #Give-Injection "Give Injection" "Needs definition"
* #Health-Education "Health Education" "Needs definition"
* #Nebulization-With-Salbutamol-NS-And-Oxygen "Nebulization With Salbutamol + N.S. + Oxygen" "Needs definition"
* #Nebulize-With-Ipravent-And-NS-And-Oxygen "Nebulize with Ipravent + N.S. + Oxygen" "Needs definition"
* #Nebulize-with-Salbutamol-And-Ipravent-And-NS-And-Oxygen "Nebulize with Salbutamol + Ipravent + N.S. + Oxygen" "Needs definition"
* #Tetanus-toxoid-0.5ml-IM-3-doses "Tetanus toxoid 0.5 ml IM - 3 doses" "Needs definition"
* #Tetanus-toxoid-0.5ml-IM-Stat "Tetanus toxoid 0.5ml IM - Stat" "Needs definition"

ValueSet: VSProcedures
Id: vs-procedure
Title: "Procedures"
Description: "Other Procedures"
* ^experimental = false
* include codes from system CSProcedures
* include codes from system CSImagingProcedures

CodeSystem: CSInvestigations
Id: cs-investigation
Title: "Investigations"
Description: "Investigations"
* ^experimental = false
* ^caseSensitive = true
* #CLOTTING-PROFILE-BT "CLOTTING PROFILE - BT" "Needs definition"
* #CLOTTING-PROFILE-CT "CLOTTING PROFILE - CT" "Needs definition"
* #CLOTTING-PROFILE-APTT "CLOTTING PROFILE - APTT" "Needs definition"
* #CLOTTING-PROFILE-INR "CLOTTING PROFILE - INR" "Needs definition"
* #UFR-Albumin "UFR - Albumin" "Needs definition"
* #UFR-Pus-cells "UFR - Pus cells" "Needs definition"
* #UFR-Red-cells "UFR - Red cells" "Needs definition"
* #UFR-Cast "UFR - Cast" "Needs definition"
* #UFR-Crystals "UFR - Crystals" "Needs definition"
* #UFR-Epithelial-cells "UFR - Epithelial cells" "Needs definition"
* #UFR-Yeast "UFR - Yeast" "Needs definition"
* #UFR-Organism "UFR - Organism" "Needs definition"
* #Urine-Microalburin "Urine Microalburin" "Needs definition"
* #Urine-AIbumin-Creatinine-Ratio "Urine AIbumin Creatinine Ratio" "Needs definition"
* #Virology-Covid-Rapid-antigen "Virology - Covid Rapid antigen" "Needs definition"
* #Thyroid-Function-Test-TSH "Thyroid Function Test - TSH" "Needs definition"
* #Thyroid-Function-Test-FT3 "Thyroid Function Test - FT3" "Needs definition"
* #Thyroid-Function-Test-FT4 "Thyroid Function Test - FT4" "Needs definition"
* #Sputum-AFB-Sputum-AFB-Sample-1 "Sputum AFB - Sputum AFB Sample 1" "Needs definition"
* #Sputum-AFB-Sputum-AFB-Sample-2 "Sputum AFB - Sputum AFB Sample 2" "Needs definition"
* #Sputum-AFB-Sputum-AFB-Sample-3 "Sputum AFB - Sputum AFB Sample 3" "Needs definition"
* #Serum-electrolyte-S.-Na "Serum electrolyte - S. Na" "Needs definition"
* #Serum-electrolyte-S.-K "Serum electrolyte - S. K" "Needs definition"
* #Serum-electrolyte-Serum-Chloride "Serum electrolyte - Serum Chloride" "Needs definition"
* #Lipid-profile-Total-Cholesterol "Lipid profile - Total Cholesterol" "Needs definition"
* #Lipid-profile-HDL-Cholesterol "Lipid profile - HDL Cholesterol" "Needs definition"
* #Lipid-profile-LDL-Cholesterol "Lipid profile - LDL Cholesterol" "Needs definition"
* #Lipid-profile-T.-Cho/HDL-Ratio "Lipid profile - T. Cho/HDL Ratio" "Needs definition"
* #Lipid-profile-Triglyceride "Lipid profile - Triglyceride" "Needs definition"
* #Lipid-profile-VLDL "Lipid profile - VLDL" "Needs definition"
* #Hepatitis-Screening-Hep-B-Surface-Antigen "Hepatitis Screening - Hep B Surface Antigen" "Needs definition"
* #Hepatitis-Screening-Hep-C-Antibody "Hepatitis Screening - Hep C Antibody" "Needs definition"
* #Hepatitis-Screening-Hep-A-Antibody "Hepatitis Screening - Hep A Antibody" "Needs definition"
* #HbA1c-HbA1c "HbA1c - HbA1c" "Needs definition"
* #FBC-BAS% "FBC - BAS%" "Needs definition"
* #FBC-EOS% "FBC - EOS%" "Needs definition"
* #FBC-LYM% "FBC - LYM%" "Needs definition"
* #FBC-MON% "FBC - MON%" "Needs definition"
* #FBC-NEU% "FBC - NEU%" "Needs definition"
* #FBC-MCV-fl "FBC - MCV (fl)" "Needs definition"
* #FBC-PLT "FBC - PLT" "Needs definition"
* #FBC-WBC-th/uL "FBC - WBC (th/uL)" "Needs definition"
* #FBC-BAS# "FBC - BAS#" "Needs definition"
* #FBC-NEU# "FBC - NEU#" "Needs definition"
* #FBC-EOS# "FBC - EOS#" "Needs definition"
* #FBC-LYM# "FBC - LYM#" "Needs definition"
* #FBC-MON# "FBC - MON#" "Needs definition"
* #FBC-RBC "FBC - RBC" "Needs definition"
* #Haemoglobin-HPLC-HGB "Haemoglobin HPLC - HGB" "Needs definition"
* #Haemoglobin-HPLC-MCH "Haemoglobin HPLC - MCH" "Needs definition"
* #Haemoglobin-HPLC-MCHC "Haemoglobin HPLC - MCHC" "Needs definition"
* #Haemoglobin-HPLC-RDW-CV "Haemoglobin HPLC - RDW-CV" "Needs definition"
* #Haemoglobin-HPLC-RDW-SD "Haemoglobin HPLC - RDW-SD" "Needs definition"
* #Haemoglobin-HPLC-HCT "Haemoglobin HPLC - HCT" "Needs definition"
* #Haemoglobin-HPLC-MPV "Haemoglobin HPLC - MPV" "Needs definition"
* #Haemoglobin-HPLC-PDW "Haemoglobin HPLC - PDW" "Needs definition"
* #Haemoglobin-HPLC-PCT "Haemoglobin HPLC - PCT" "Needs definition"
* #Haemoglobin-HPLC-PLCC "Haemoglobin HPLC - PLCC" "Needs definition"
* #Haemoglobin-HPLC-PLCR "Haemoglobin HPLC - PLCR" "Needs definition"
* #ESR-ESR-1st-Hour "ESR - ESR 1st Hour" "Needs definition"
* #Dengue-Test-NS1-Antigen "Dengue Test - NS1 Antigen" "Needs definition"
* #Dengue-Test-Dengue-Ig-M "Dengue Test - Dengue Ig M" "Needs definition"
* #Dengue-Test-Dengue-Ig-G "Dengue Test - Dengue Ig G" "Needs definition"
* #Blood-Sugar-FBS "Blood Sugar - FBS" "Needs definition"
* #HbA1c-HBA1C "HbA1c - HBA1C" "Needs definition"
* #HbA1c-PPBS "HbA1c - PPBS" "Needs definition"
* #HbA1c-RBS "HbA1c - RBS" "Needs definition"
* #HbA1c-OGTT "HbA1c - OGTT" "Needs definition"
* #Serum-Creatinine-S-Creatinine "Serum Creatinine - S Creatinine" "Needs definition"
* #Blood-Urea-Blood-Urea "Blood Urea - Blood Urea" "Needs definition"
* #S-Uric-Acid "S Uric Acid" "Needs definition"
* #Serum-Calcium-Total "Serum Calcium-Total" "Needs definition"
* #Serum-Magnesium "Serum Magnesium" "Needs definition"
* #Serum-Phosphorous "Serum Phosphorous" "Needs definition"
* #Corrected-Calcium "Corrected Calcium" "Needs definition"
* #CRP-C-Reactive-Protein "CRP - C Reactive Protein" "Needs definition"
* #S-LDH-LDH "S LDH - LDH" "Needs definition"
* #Creatine-Kinase-Creatinine-Kinase "Creatine Kinase - Creatinine Kinase" "Needs definition"
* #Stool-Full-Report "Stool Full Report" "Needs definition"
* #S.-Vitamin-D-Level "S. Vitamin D Level" "Needs definition"
* #Rheumaloid-Facior "Rheumaloid Facior" "Needs definition"
* #Blood-Picture "Blood Picture" "Needs definition"
* #S-Prostate-Specific-Antigen "S Prostate Specific Antigen" "Needs definition"
* #serum-Amylase-units/L "serum Amylase (units/L)" "Needs definition"
* #Rheumatoid-Factor "Rheumatoid Factor" "Needs definition"
* #Iron-Studies "Iron Studies" "Needs definition"
* #S.-Uric-Acid "S. Uric Acid" "Needs definition"
* #Liver-profile-SGOT-U/L "Liver profile - SGOT U/L" "Needs definition"
* #SGOT/PT-SGPT-U/L "SGOT/PT - SGPT U/L" "Needs definition"
* #S-Alkaline-Phosphatasee-Alakaline-Phosphatase-IU/L "S Alkaline Phosphatasee - Alakaline Phosphatase IU/L" "Needs definition"
* #S.-Bilirubin-Bilirubin-Direct-mg/dl "S. Bilirubin - Bilirubin Direct mg/dl" "Needs definition"
* #S.-Bilirubin-Bilirubin-Total-mg/dl "S. Bilirubin - Bilirubin Total mg/dl" "Needs definition"
* #Serum-Prolein-Total-Protein-g/dl "Serum Prolein - Total Protein g/dl" "Needs definition"
* #S.-Amilase-Bilirubin-Indirect-mg/dl "S. Amilase - Bilirubin Indirect mg/dl" "Needs definition"
* #S.-ALP-Serum-albumin "S. ALP - Serum albumin" "Needs definition"
* #S.-Electrolyte-Globulin "S. Electrolyte - Globulin" "Needs definition"
* #Albumin-/-Globulin-Ratio "Albumin / Globulin Ratio" "Needs definition"
* #S-Gamma-GT-S-Gamma-GT "S Gamma GT - S Gamma GT" "Needs definition"
* #Liver-Enzymes "Liver Enzymes" "Needs definition"
* #Alpha-fetoprotein "Alpha-fetoprotein" "Needs definition"
* #Hepatitis-Screening "Hepatitis Screening" "Needs definition"
* #CSF "CSF" "Needs definition"
* #Renal-Function-Tests "Renal Function Tests" "Needs definition"
* #Stool-examination "Stool examination" "Needs definition"
* #Urinalysis "Urinalysis" "Needs definition"
* #Urine-for-BJP "Urine for BJP" "Needs definition"
* #Cytology "Cytology" "Needs definition"
* #Antibody-testing "Antibody testing" "Needs definition"
* #Biochem-basic-tests "Biochem - basic tests" "Needs definition"

ValueSet: VSInvestigations
Id: vs-investigation
Title: "Investigations"
Description: "Investigations"
* ^experimental = false
* include codes from system CSInvestigations

CodeSystem: CSMedicationNames
Id: cs-medication-name
Title: "Medication Names"
Description: "Medication Names"
* ^experimental = false
* ^caseSensitive = true
* #Alpha-Chole-Calciferol "Alpha Chole Calciferol" "Needs definition"
* #Acarbose "Acarbose" "Needs definition"
* #Aciclovir "aciclovir" "Needs definition"
* #Alendronate "Alendronate" "Needs definition"
* #Allopurinol "Allopurinol" "Needs definition"
* #Alprazolam "Alprazolam" "Needs definition"
* #Amiodarone "Amiodarone" "Needs definition"
* #Amitriptyline "amitriptyline" "Needs definition"
* #Amlodipine "Amlodipine" "Needs definition"
* #Amoxycillin "Amoxycillin" "Needs definition"
* #Ascorbic-Acid "Ascorbic acid" "Needs definition"
* #Aspirin "aspirin" "Needs definition"
* #Atorvastatin "atorvastatin" "Needs definition"
* #Cetrizine "Cetrizine" "Needs definition"
* #Chloramphenicol "chloramphenicol" "Needs definition"
* #Chlorpheniramine "chlorpheniramine" "Needs definition"
* #Chlorpromazine "chlorpromazine" "Needs definition"
* #Cilnidipine "Cilnidipine" "Needs definition"
* #Ciprofloxacin "ciprofloxacin" "Needs definition"
* #Clarythromycin "clarythromycin" "Needs definition"
* #Clinidipine "clinidipine" "Needs definition"
* #Clobazam "Clobazam" "Needs definition"
* #Clonazepam "clonazepam" "Needs definition"
* #Clopidogrel "clopidogrel" "Needs definition"
* #Clotrimazole "Clotrimazole" "Needs definition"
* #Cloxacillin "Cloxacillin" "Needs definition"
* #Co-Q-Enzyme "Co - Q enzyme" "Needs definition"
* #Co-Amoxiclav "Co-amoxiclav" "Needs definition"
* #Co-Careldopa-Carbidopa-Bp+Levodopa-Bp "Co-Careldopa (Carbidopa BP + Levodopa BP)" "Needs definition"
* #Concer "concer" "Needs definition"
* #Cotrimoxazole "cotrimoxazole" "Needs definition"
* #Crepe-Bandage "crepe bandage" "Needs definition"
* #Dapaglifiozin "Dapaglifiozin" "Needs definition"
* #Dapoxetine "Dapoxetine" "Needs definition"
* #Desioratadine "Desioratadine" "Needs definition"
* #Dexamethasone "dexamethasone" "Needs definition"
* #Diamicron "Diamicron" "Needs definition"
* #Diazepam "diazepam" "Needs definition"
* #Diclofenac-Na "diclofenac-Na" "Needs definition"
* #Diethylcarbamazine-Hetrazan "diethylcarbamazine (Hetrazan)" "Needs definition"
* #Digoxin "digoxin" "Needs definition"
* #Diltiazem "Diltiazem" "Needs definition"
* #Domperidone "Domperidone" "Needs definition"
* #Donepezil "Donepezil" "Needs definition"
* #Doxycycline "Doxycycline" "Needs definition"
* #Asthalin "Asthalin" "Needs definition"
* #Beclate "Beclate" "Needs definition"
* #Beclomethazone-Diproprionate "Beclomethazone diproprionate" "Needs definition"
* #Dp-Haler "DP Haler" "Needs definition"
* #Salmetrol+Fluticazone "Salmetrol + Fluticazone" "Needs definition"
* #Ecosprin "Ecosprin" "Needs definition"
* #Empagliflozin "Empagliflozin" "Needs definition"
* #Enalapril "enalapril" "Needs definition"
* #Erythromycin "erythromycin" "Needs definition"
* #Erythropoietin "Erythropoietin" "Needs definition"
* #Ezetimibe "Ezetimibe" "Needs definition"
* #Famotidine "Famotidine" "Needs definition"
* #Fenofibrate "Fenofibrate" "Needs definition"
* #Ferrous-Fumarate "ferrous fumarate" "Needs definition"
* #Ferrous-Sulphate "ferrous sulphate" "Needs definition"
* #Finasteride "Finasteride" "Needs definition"
* #Flucloxacillin "FLUCLOXACILLIN" "Needs definition"
* #Flunarizine "Flunarizine" "Needs definition"
* #Fluoxetine "Fluoxetine" "Needs definition"
* #Folic-Acid "folic acid" "Needs definition"
* #Frisium "frisium" "Needs definition"
* #Frusemide "frusemide" "Needs definition"
* #Furazolidone "furazolidone" "Needs definition"
* #Fusigel "FUSIGEL" "Needs definition"
* #Gabapentin "Gabapentin" "Needs definition"
* #Glibenclamide-Diaonil "glibenclamide (Diaonil)" "Needs definition"
* #Gliclazide "gliclazide" "Needs definition"
* #Glimepride "Glimepride" "Needs definition"
* #Glucophage "Glucophage" "Needs definition"
* #Glycery/Trinitrate-Gtn-Sublingual "glycery/trinitrate (GTN) sublingual" "Needs definition"
* #Glycomet "Glycomet" "Needs definition"
* #Griseofulvin "griseofulvin" "Needs definition"
* #Hydrochlorothiazide "hydrochlorothiazide" "Needs definition"
* #Hydrocortisone "Hydrocortisone" "Needs definition"
* #Hyosine-Butylbromide-Buscopan "Hyosine butylbromide (Buscopan)" "Needs definition"
* #Ibuprofen "ibuprofen" "Needs definition"
* #Imipramine "imipramine" "Needs definition"
* #Indapamide "Indapamide" "Needs definition"
* #Indomethacin "indomethacin" "Needs definition"
* #Insulin "insulin" "Needs definition"
* #Irbesartan "irbesartan" "Needs definition"
* #Isosorbide-Dinitrate-Isdn "isosorbide dinitrate (ISDN)" "Needs definition"
* #Isosorbide-Mononitrate "isosorbide mononitrate" "Needs definition"
* #Ivabradine "Ivabradine" "Needs definition"
* #Kcl "KCL" "Needs definition"
* #Lamotrigine "Lamotrigine" "Needs definition"
* #Levetiracetam "Levetiracetam" "Needs definition"
* #Levofloxacin "Levofloxacin" "Needs definition"
* #Linagliptin "linagliptin" "Needs definition"
* #Lithium-Carbonate "lithium carbonate" "Needs definition"
* #Losartan "Losartan" "Needs definition"
* #Methyl-Salicylate "Methyl Salicylate" "Needs definition"
* #Magnesium-Sulphate "magnesium sulphate" "Needs definition"
* #Manorest "Manorest" "Needs definition"
* #Beclomethasone "Beclomethasone" "Needs definition"
* #Ipravent "Ipravent" "Needs definition"
* #Salbutamol-Asthalin "Salbutamol (Asthalin)" "Needs definition"
* #Salmetrol/Fluticazone "Salmetrol / Fluticazone" "Needs definition"
* #Seroflo "Seroflo" "Needs definition"
* #Tiova "Tiova" "Needs definition"
* #Mebendazole "Mebendazole" "Needs definition"
* #Metalazone "Metalazone" "Needs definition"
* #Metaprolol "Metaprolol" "Needs definition"
* #Metformin "Metformin" "Needs definition"
* #Methotrexate "Methotrexate" "Needs definition"
* #Methyl-Prednisolone "Methyl Prednisolone" "Needs definition"
* #Methyldopa-Aldomet "methyldopa (Aldomet)" "Needs definition"
* #Metronidazole "metronidazole" "Needs definition"
* #Miconazole "MICONAZOLE" "Needs definition"
* #Minipress "Minipress" "Needs definition"
* #Montelukast "Montelukast" "Needs definition"
* #Mycostatin "mycostatin" "Needs definition"
* #Nebivolol "Nebivolol" "Needs definition"
* #Neuroton "Neuroton" "Needs definition"
* #Nicorandil "Nicorandil" "Needs definition"
* #Nifedipine "nifedipine" "Needs definition"
* #Nitrocontin "Nitrocontin" "Needs definition"
* #Nitrofurantoin "Nitrofurantoin" "Needs definition"
* #Noklot "Noklot" "Needs definition"
* #Normal-Saline-Nasal-Drops "normal saline nasal drops" "Needs definition"
* #Olanzapine "olanzapine" "Needs definition"
* #Omeprazole "omeprazole" "Needs definition"
* #Oral-Rehydration-Salts "oral rehydration salts" "Needs definition"
* #Pantaprazole "Pantaprazole" "Needs definition"
* #Paracetamol "paracetamol" "Needs definition"
* #Penicillin "penicillin" "Needs definition"
* #Persantin "Persantin" "Needs definition"
* #Capsulephenobarbital-Luminal "Capsulephenobarbital (Luminal)" "Needs definition"
* #Phenytoin-Sodium "phenytoin sodium" "Needs definition"
* #Pioglitazone "Pioglitazone" "Needs definition"
* #Potassium-Permanganate "potassium permanganate" "Needs definition"
* #Prazosin "prazosin" "Needs definition"
* #Pregabalin "Pregabalin" "Needs definition"
* #Prednisolone "prednisolone" "Needs definition"
* #Prochlorperazine-Stemetil "prochlorperazine (Stemetil)" "Needs definition"
* #Promethazine-Phenergan "promethazine (Phenergan)" "Needs definition"
* #Propranolol "propranolol" "Needs definition"
* #Propyithiouracil "Propyithiouracil" "Needs definition"
* #Pulse-Tri-Omega "Pulse Tri Omega" "Needs definition"
* #Pyrantel-Pamoate "pyrantel pamoate" "Needs definition"
* #Quetiapine "Quetiapine" "Needs definition"
* #Ranalazine "Ranalazine" "Needs definition"
* #Rifaximin "Rifaximin" "Needs definition"
* #Risperidone "risperidone" "Needs definition"
* #Ropinirole "Ropinirole" "Needs definition"
* #Rosuvastatin "Rosuvastatin" "Needs definition"
* #Salbutamol "salbutamol" "Needs definition"
* #Sertalin "Sertalin" "Needs definition"
* #Sildenafil "sildenafil" "Needs definition"
* #Sinemet "Sinemet" "Needs definition"
* #Sitagliptin "sitagliptin" "Needs definition"
* #Sodium-Bicarbonate-Nahco3 "Sodium Bicarbonate (NaHCO3)" "Needs definition"
* #Sodium-Bicarbonate-Ear-Drops "sodium bicarbonate ear drops" "Needs definition"
* #Sodium-Valproate "sodium valproate" "Needs definition"
* #Soframycin-Cream "Soframycin Cream" "Needs definition"
* #Spacer-Device "Spacer Device" "Needs definition"
* #Spironolactone "spironolactone" "Needs definition"
* #Stematil "Stematil" "Needs definition"
* #Sulphasalazine "sulphasalazine" "Needs definition"
* #Syndpa "Syndpa" "Needs definition"
* #Tamsulosin "tamsulosin" "Needs definition"
* #Tazloc "tazloc" "Needs definition"
* #Telmisartan "Telmisartan" "Needs definition"
* #Theophylline "theophylline" "Needs definition"
* #Thiamin "Thiamin" "Needs definition"
* #Thyroxine "thyroxine" "Needs definition"
* #Tolbutamide "tolbutamide" "Needs definition"
* #Topiramate "Topiramate" "Needs definition"
* #Tramadol "tramadol" "Needs definition"
* #Trifluoperazine-Stelazine "trifluoperazine (Stelazine)" "Needs definition"
* #Urimax "Urimax" "Needs definition"
* #Ursodiol "Ursodiol" "Needs definition"
* #Verapamil "verapamil" "Needs definition"
* #Vildagliptin "vildagliptin" "Needs definition"
* #Vitamin-A-&-D "vitamin A & D" "Needs definition"
* #Vitamin-B "vitamin B" "Needs definition"
* #Vitamin-E "Vitamin E" "Needs definition"
* #Warfarin "warfarin" "Needs definition"
* #Zinc-Sulphate "Zinc Sulphate" "Needs definition"

ValueSet: VSMedicationNames
Id: vs-medication-name
Title: "Medication Names"
Description: "Medication Names"
* ^experimental = false
* include codes from system CSMedicationNames

CodeSystem: CSImagingProcedures
Id: cs-procedure-imaging
Title: "Procedures"
Description: "Imaging Procedures"
* ^experimental = false
* ^caseSensitive = true
* #X-Ray "X-Ray" "Needs definition"
* #MRI "MRI" "Needs definition"
* #Ultrasound "Ultrasound" "Needs definition"
* #CT "CT" "Needs definition"
* #Fluoroscopy "Fluoroscopy" "Needs definition"
* #Angiography "Angiography" "Needs definition"
* #Mammography "Mammography" "Needs definition"
* #Breast-Tomosynthesis "Breast Tomosynthesis" "Needs definition"
* #PET "PET" "Needs definition"
* #SPECT "SPECT" "Needs definition"
* #Endoscopy "Endoscopy" "Needs definition"
* #Microscopy "Microscopy" "Needs definition"
* #Whole-Slide-Imaging "Whole Slide Imaging" "Needs definition"
* #OCT "OCT" "Needs definition"

ValueSet: VSImagingProcedures
Id: vs-procedure-imaging
Title: "Procedures"
Description: "Imaging Procedures"
* ^experimental = false
* include codes from system CSImagingProcedures