# .github/workflows/build-ig.yml
name: Build & Publish IG
on:
  push:
    branches: [ master ]
jobs:
  build:
   runs-on: [DESKTOP-T9TTC9A]   # <- your runner's labels
    defaults:
      run:
        shell: pwsh
   
    steps:
      - uses: actions/checkout@v4
      - uses: qligier/fhir-ig-action@v0.3.0
        with:
          sushi: latest          # run SUSHI before IG Publisher
          ig-publisher: latest   # build the HTML
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
