---
name: 'Build & Publish IG'
'on':
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on:
      - 'self-hosted'
      - 'windows'
      - 'x64'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'qligier/fhir-ig-action@v0.3.0'
        with:
          sushi: 'latest'
          ig-publisher: 'latest'
      - name: 'Deploy to Pages'
        uses: 'peaceiris/actions-gh-pages@v3'
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          publish_dir: 'output'
